spring:
  application:
    name: TinyHappyTrip

  resource:
    static-locations: file:///C:/tinyhappytrip/user/

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 394897395147-hf6n8skr8mlu9jnshge5tqguo4n0ngkm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: W1KwUoXzffIYOAZSAw4g
            client-secret: QqIgwYSoki
            client-name: Naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - nickname
              - email
              - profile_image
          kakao:
            client-id: e86f69e6ec0994a1f096b9953c71f6d7
            client-secret: hU1dFQ2Dg9oD46GDtfeGhqhY9BGhRB8m
            client-name: Kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id

  datasource:
    url: jdbc:mysql://localhost:3306/tinyhappytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ssafy
      password: ssafy

  mail:
    host: smtp.gmail.com
    port: 587
    username: mrcsbin@gmail.com
    password: rrfbmxhrzgmnevhh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: mapper/*/*.xml
  type-aliases-package: com.tinyhappytrip.*.mapper
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: 32fb489c2d3908512124353a733d2f58bcbc531fffb3cee4d8fe674ef97628e2
  token-validity-in-seconds: 3600

youtube:
  api:
    key: AIzaSyB6MN5BHZp6qCqGtRXJvRgUtc4CpsnL6e8



# 싸피
#image:
#  user: C:\\tinyhappytrip\\user
#  story: C:\\tinyhappytrip\\story
#  playlist: C:\\tinyhappytrip\\playlist

# 성빈
image:
  user: /Users/sungbincho/Desktop/tinyhappytrip/user
  story: /Users/sungbincho/Desktop/tinyhappytrip/story
  collection: /Users/sungbincho/Desktop/tinyhappytrip/collection

# 수민
#image:
#  user: /Users/soom/Desktop/tinyhappytrip/user
#  story: /Users/soom/Desktop/tinyhappytrip/story
#  playlist: /Users/soom/Desktop/tinyhappytrip/collection
