spring:
  application:
    name: TinyHappyTrip

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 394897395147-hf6n8skr8mlu9jnshge5tqguo4n0ngkm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: W1KwUoXzffIYOAZSAw4g
            client-secret: QqIgwYSoki
            client-name: Naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - email
              - profile_image

          kakao:
            client-id: b0401570b6affe834162d8d8b65675e2
            client-secret: AfvHtEb98PkAxe0xgCCoxlkyjw1jlrSS
            client-name: Kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_image
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ssafy
      password: ssafy

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.tinyhappytrip.*.mapper
  configuration:
    map-underscore-to-camel-case: true


servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB
    # window
    location: c:\\Project\\tinyhappytrip
    # mac
#    location: e:\\Project\\tinyhappytrip
#    location: /Users/soom/Desktop/tinyhappytrip

